name: Generate SBOM

on:
  push:
    branches:
      - master # Of 'main', afhankelijk van je repo

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Download CycloneDX CLI
        run: |
          # Download binary en hash
          curl -sSL -o cyclonedx https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64
          curl -sSL -o raw.sha256 https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64.sha256

          # Herschrijf hash bestand in juist formaat
          echo "$(cat raw.sha256)  cyclonedx" > cyclonedx.sha256

          # Controleer hash
          sha256sum -c cyclonedx.sha256

          # Maak binary uitvoerbaar
          chmod +x cyclonedx

      - name: Genereer SBOM (CycloneDX)
        run: ./cyclonedx sbom --output sbom.json --input . --type npm

      - name: Upload SBOM als artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
