name: Generate SBOM

on:
  push:
    branches:
      - master # of 'master' als je dat gebruikt

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Generate SBOM with CycloneDX
        run: npx @cyclonedx/bom -o sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
