name: Generate SBOM

on:
  push:
    branches:
      - master # of 'main' als je repo zo heet

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Download CycloneDX CLI (zonder checksum)
        run: |
          # Download de binary
          curl -sSL -o cyclonedx https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64

          # Maak uitvoerbaar
          chmod +x cyclonedx

          # Toon versie als controle
          ./cyclonedx version

      - name: Genereer SBOM
        run: ./cyclonedx sbom --output sbom.json --input . --type npm

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
